"""empty message

Revision ID: 0489a323046c
Revises: 092ecda4814d
Create Date: 2022-03-03 00:50:11.190871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0489a323046c'
down_revision = '092ecda4814d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('about', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'about')
    # ### end Alembic commands ###
