"""empty message

Revision ID: 092ecda4814d
Revises: 28c85c351521
Create Date: 2022-03-02 23:36:38.240149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092ecda4814d'
down_revision = '28c85c351521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('wool', sa.String(length=50), nullable=True))
    op.add_column('category', sa.Column('origin', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'origin')
    op.drop_column('category', 'wool')
    # ### end Alembic commands ###
