"""empty message

Revision ID: 28c85c351521
Revises: da9b081b4ee6
Create Date: 2022-03-02 20:25:30.287002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c85c351521'
down_revision = 'da9b081b4ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cats', sa.Column('cat_pic', sa.String(), nullable=True))
    op.drop_column('users', 'favourite_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favourite_color', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('cats', 'cat_pic')
    # ### end Alembic commands ###
