"""empty message

Revision ID: 4433637c9370
Revises: c1944cd61cf9
Create Date: 2022-03-01 14:59:28.682721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4433637c9370'
down_revision = 'c1944cd61cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cats', sa.Column('categories', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cats', 'categories')
    # ### end Alembic commands ###
