"""empty message

Revision ID: 7aa26ec4503e
Revises: 9ac319bfc74a
Create Date: 2022-03-01 13:13:04.775117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa26ec4503e'
down_revision = '9ac319bfc74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cats_breed',
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.Column('breeds_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['breeds_id'], ['breeds.id'], ),
    sa.ForeignKeyConstraint(['cat_id'], ['cats.id'], )
    )
    op.drop_constraint('cats_category_fkey', 'cats', type_='foreignkey')
    op.drop_column('cats', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cats', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cats_category_fkey', 'cats', 'breeds', ['category'], ['id'])
    op.drop_table('cats_breed')
    # ### end Alembic commands ###
