"""empty message

Revision ID: 8417d81fc859
Revises: 4b568895bc48
Create Date: 2022-03-01 01:48:41.668241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8417d81fc859'
down_revision = '4b568895bc48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('breeds')
    op.add_column('cats', sa.Column('poster_id', sa.Integer(), nullable=True))
    op.drop_constraint('cats_user_id_fkey', 'cats', type_='foreignkey')
    op.create_foreign_key(None, 'cats', 'users', ['poster_id'], ['id'])
    op.drop_column('cats', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cats', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cats', type_='foreignkey')
    op.create_foreign_key('cats_user_id_fkey', 'cats', 'users', ['user_id'], ['id'])
    op.drop_column('cats', 'poster_id')
    op.create_table('breeds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='breeds_pkey')
    )
    # ### end Alembic commands ###
