"""empty message

Revision ID: 9ac319bfc74a
Revises: 40df4493b7a9
Create Date: 2022-03-01 02:44:45.517184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac319bfc74a'
down_revision = '40df4493b7a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'breeds', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'breeds', type_='unique')
    # ### end Alembic commands ###
