"""empty message

Revision ID: 9bb0a907165d
Revises: 4433637c9370
Create Date: 2022-03-01 22:02:18.890498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb0a907165d'
down_revision = '4433637c9370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cats_category')
    op.add_column('users', sa.Column('profile_pic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    op.create_table('cats_category',
    sa.Column('cat_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['cats.id'], name='cats_category_cat_id_fkey'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='cats_category_category_id_fkey')
    )
    # ### end Alembic commands ###
