"""empty message

Revision ID: c1944cd61cf9
Revises: 7aa26ec4503e
Create Date: 2022-03-01 14:52:51.812857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1944cd61cf9'
down_revision = '7aa26ec4503e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cats_category',
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['cats.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], )
    )
    op.drop_table('cats_breed')
    op.drop_table('breeds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeds',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('breeds_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='breeds_pkey'),
    sa.UniqueConstraint('name', name='breeds_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('cats_breed',
    sa.Column('cat_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('breeds_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['breeds_id'], ['breeds.id'], name='cats_breed_breeds_id_fkey'),
    sa.ForeignKeyConstraint(['cat_id'], ['cats.id'], name='cats_breed_cat_id_fkey')
    )
    op.drop_table('cats_category')
    op.drop_table('category')
    # ### end Alembic commands ###
